#  errors:
#    rule_name: severity(error/warning/info=lint)
#  group errors ---> MAX SEVERITY = error
#  group style ---> MAX SEVERITY = warning

analyzer:
  exclude: [build/**]
  errors:
    # group error
    # group style
    always_declare_return_types: warning
    always_put_control_body_on_new_line: warning
    always_specify_types: ignore
    avoid_annotating_with_dynamic: ignore
    avoid_classes_with_only_static_members: ignore
    avoid_function_literals_in_foreach_calls: ignore
    avoid_init_to_null: warning
    avoid_positional_boolean_parameters: info
    avoid_single_cascade_in_expression_statements: warning
    avoid_types_on_closure_parameters: ignore
    await_only_futures: warning
    cascade_invocations: warning
    camel_case_types: warning
    comment_references: info
    directives_ordering: info
    empty_constructor_bodies: warning
    join_return_with_assignment: warning
    library_names: warning
    library_prefixes: warning
    non_constant_identifier_names: warning
    omit_local_variable_types: ignore
    parameter_assignments: warning
    prefer_collection_literals: warning
    prefer_conditional_assignment: warning
    prefer_expression_function_bodies: warning
    prefer_final_fields: warning
    prefer_final_locals: ignore
    prefer_foreach: warning
    prefer_interpolation_to_compose_strings: warning
    prefer_is_empty: warning
    prefer_is_not_empty: warning
    public_member_api_docs: info
    slash_for_doc_comments: info
    sort_constructors_first: warning
    type_annotate_public_apis: info
    unawaited_futures: warning
    unnecessary_brace_in_string_interps: warning
    unnecessary_getters_setters: info
    unnecessary_lambdas: warning
    unnecessary_null_in_if_null_operators: warning
    unnecessary_parenthesis: warning
    unnecessary_this: warning
    uri_has_not_been_generated: ignore
  plugins:
    -angular


# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - always_specify_types
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_as
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - cascade_invocations
    - close_sinks
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_bool_in_asserts
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_locals
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - public_member_api_docs
    - recursive_getters
    - slash_for_doc_comments
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - super_goes_last
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps
