name: whalefeed
description: webapp
version: 0.1.5
homepage:
author: ramon <rguimerao@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0 # https://github.com/dart-lang/angular/releases
  angular_analyzer_plugin: ^0.0.17+3 # https://github.com/dart-lang/angular_analyzer_plugin/releases
  angular_components: ^0.9.0 # https://github.com/dart-lang/angular_components/releases
  angular_router: ^2.0.0-alpha # https://pub.dartlang.org/packages/angular_router#-versions-tab-
  angular_forms: ^2.0.0 # https://pub.dartlang.org/packages/angular_forms#-versions-tab-
  dart_toast: ^0.2.1 # https://pub.dartlang.org/packages/dart_toast#-versions-tab-
  firebase: ^5.0.0 # https://github.com/firebase/firebase-dart/releases
  linter: ^0.1.58 # https://github.com/dart-lang/linter/releases

dev_dependencies:
  angular_test: ^2.0.0-beta
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc
